export const TOGGLE_SETTINGS_VISIBILITY = 'TOGGLE_SETTINGS_VISIBILITY';
export const SET_ACTIVE = 'SET_ACTIVE';
export const SET_BUTTON_TEXT = 'SET_BUTTON_TEXT';
export const SET_SECONDS_LEFT = 'SET_SECONDS_LEFT';
export const FINISHED_TIMER = 'FINISHED_TIMER';
export const CHANGE_TIMER_MODE = 'CHANGE_TIMER_MODE';
export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';
export const APPLY_SETTINGS = 'APPLY_SETTINGS';